export const Action = {
  SIGNIN: "SIGNIN",
  SIGNOUT: "SIGNOUT",
  SIGNUP: "SIGNUP",
  SIGNIN_GOOGLE: "SIGNIN_GOOGLE",
  SIGNIN_FACEBOOK: "SIGNIN_FACEBOOK",
};

export const Mutation = {
  SET_USER: "SET_USER",
  SET_ERROR: "SET_ERROR",
  CLEAR_ERROR: "CLEAR_ERROR",
  SET_LOADING: 'SET_LOADING'
};
